Inventory/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from register import views as v


urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", v.register, name="register"),
	path('', v.loginPage, name="login"),  
    path('logout/', v.logoutUser, name="logout"),
    path('performance/', include('products.urls', namespace="products")),
    path('upload/', include('csvs.urls', namespace="csvs")),
    path('customers/', include('customers.urls', namespace="customer"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

csvs/urls.py
from django.urls import path
from .views import upload_file_view, upload_product_file_view

app_name = 'csvs'

urlpatterns = [
    path('purchase/', upload_file_view, name='upload-view'),
    path('product/', upload_product_file_view, name='upload-view-product'),
]

customers/urls.py
from django.urls import path
from .views import customer_corr_view

app_name = 'customers'

urlpatterns = [
    path('', customer_corr_view, name='main-customer-view'),
]

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('', chart_select_view, name='main-products-view'),
    path('add/',add_purchase_view, name='add-purchase-view'),
    path('sales/',sales_dist_view, name='sales-view'),    
    path('items/',items_list,name='items_list_url'),
    path('demand/',demand_list,name='demand_list_url'),
    path('calculations/',calculations,name='calculations_url'),
    path('demand/create/',DemandCreate,name='demand_create_url'),
    path('item/create/',ItemCreate,name='item_create_url'),
    path('delete_items/<str:pk>/', delete_items, name="delete_items"),
    path('update_item/<str:pk>/',update_items,name="update_item"),  
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!--custom css-->
  <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
  <script src="semantic/dist/semantic.min.js"></script>
  <link rel="stylesheet" type="text/css" href = "c:/Users/Dell/Desktop/congenial-train-master/static_project/style.css">
  <title>
      {% block title %}
        Inventory Project ..
      {% endblock %}
  </title>
</head>
<body>
  <style>
    .hello-msg{
      font-size: 18px;
      color: #fff;
      margin-right: 20px;
    }
  </style>

  {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active"><a class="nav-link" href="{% url 'products:demand_list_url' %}">History</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'products:items_list_url' %}">Inventory Data</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'products:demand_create_url' %}">Sales</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'products:calculations_url' %}">Analysis</a></li>
          
          <li class="nav-item active"><a class="nav-link" href="{% url 'products:main-products-view' %}">performance</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'products:add-purchase-view' %}">add_records</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'products:sales-view' %}">sales</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'customers:main-customer-view' %}">customers</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'csvs:upload-view' %}">upload</a></li>
        </ul>
      </div>
      <span class="hello-msg">Welcome , {{  request.user}}</span>
      <span ><a  class="hello-msg" href="{% url 'logout' %}">Logout</a></span>
    </nav>
  {% endif %}

  <div class="container mt-5">
    <div class="row">
      <!--div class="col-6 offset-md-2"-->
      <div class="ui container">
        {% block content %}
            
        {%  endblock %}
      </div>
    </div>
  </div>
  
</body>
</html>

templates/base1.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
       <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <!--Custom css ADD HERE-->
        <link rel="stylesheet" type="text/css" href={% static 'style.css' %}>
        <!-- semantic UI -->
        <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    
        <title>performance {% block title %}{% endblock title %}</title>
    </head>
    <body>
        {% include 'navbar.html'%}
        <div class="ui container">
            {% block content %}
            {% endblock content %}
        </div>

        {% block scripts %}
        {% endblock scripts %}
    
        <!--Custom js ADD HERE-->
        <script type='text/javascript' src = {% static 'main.js' %}></script>
    </body>
</html>

templates/navbar.html
{% url 'products:main-products-view' as path_to_performance %}
{% url 'products:add-purchase-view' as path_to_adding_records %}
{% url 'csvs:upload-view' as path_to_upload %}
{% url 'csvs:upload-view-product' as path_to_upload_product %}
{% url 'customers:main-customer-view' as path_to_customers %}
{% url 'products:sales-view' as path_to_sales %}
{% url 'products:demand_list_url' as path_to_demand_list %}
{% url 'products:items_list_url' as path_to_items_list %}
{% url 'products:demand_create_url' as path_to_demand_create %}
{% url 'products:calculations_url' as path_to_calculations %}

<div class="ui inverted segment">
    <div class="ui inverted secondary pointing menu">
        <a class="item">Home</a>
        <a href="{% url 'products:demand_list_url' %}" class="{% if request.path == path_to_demand_list %}active{% endif %} item">History</a>
        <a href="{% url 'products:items_list_url' %}" class="{% if request.path == path_to_items_list %}active{% endif %} item">Inventory Data</a>
        <a href="{% url 'products:demand_create_url' %}" class="{% if request.path == path_to_demand_create %}active{% endif %} item">Sales</a>
        <a href="{% url 'products:calculations_url' %}" class="{% if request.path == path_to_calculations %}active{% endif %} item">Analysis</a>

        <a href={{path_to_performance}} class="{% if request.path == path_to_performance %}active{% endif %} item">performance</a>
        <a href={{path_to_adding_records}} class="{% if request.path == path_to_adding_records %}active{% endif %} item">add_records</a>
        <a href={{path_to_sales}} class="{% if request.path == path_to_sales %}active{% endif %} item">sales</a>
        <a href={{path_to_customers}} class="{% if request.path == path_to_customers %}active{% endif %} item">customers</a>
        <a href={{path_to_upload}} class="{% if request.path == path_to_upload %}active{% endif %} item">upload</a>   
        <a href={{path_to_upload_product}} class="{% if request.path == path_to_upload_product %}active{% endif %} item">upload products</a>            
    </div>
</div>