Inventory/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from register import views as v


urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", v.register, name="register"),
	path('', v.loginPage, name="login"),  
    path('logout/', v.logoutUser, name="logout"),
    path('performance/', include('products.urls', namespace="products")),
    path('upload/', include('csvs.urls', namespace="csvs")),
    path('customers/', include('customers.urls', namespace="customer"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

csvs/urls.py
from django.urls import path
from .views import upload_file_view, upload_product_file_view

app_name = 'csvs'

urlpatterns = [
    path('purchase/', upload_file_view, name='upload-view'),
    path('product/', upload_product_file_view, name='upload-view-product'),
]

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('', chart_select_view, name='main-products-view'),
    path('add/',add_purchase_view, name='add-purchase-view'),
    path('sales/',sales_dist_view, name='sales-view'),    
    path('items/',items_list,name='items_list_url'),
    path('demand/',demand_list,name='demand_list_url'),
    path('calculations/',calculations,name='calculations_url'),
    path('demand/create/',DemandCreate,name='demand_create_url'),
    path('item/create/',ItemCreate,name='item_create_url'),
    path('delete_items/<str:pk>/', delete_items, name="delete_items"),
    path('update_item/<str:pk>/',update_items,name="update_item"),  
]

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import math
import scipy.stats as st
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# validation

def validate_even(value):
    if value > 100 or value == 0:
        raise ValidationError(
            _('%(value)s is not in between 0 and 100 percent'),
            params={'value': value},
        )
def validate_zero(value):
    if value == 0:
        raise ValidationError(
            _('%(value)s cant be zero'),
            params={'value': value},
        )

# Create your models here.

class Product(models.Model):
    user                 = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="items")
    name                 = models.CharField(max_length=220)
    date                 = models.DateTimeField(auto_now_add=True)
    lead_time            = models.PositiveIntegerField(default='0',blank=True,null=True,validators=[validate_zero])
    service_level        = models.PositiveIntegerField(default='90',blank=True,null=True,validators=[validate_even])
    standard_deviation   = models.PositiveIntegerField(default='5',blank=True,null=True)
    carrying_cost        = models.PositiveIntegerField(default='12',blank=False,validators=[validate_even],help_text='Enter as percentage of unit cost')
    ordering_cost        = models.PositiveIntegerField(default='0',blank=False,null=True)
    unit_costprice       = models.PositiveIntegerField(default='0',blank=False,null=True,validators=[validate_zero])
    average_daily_demand = models.PositiveIntegerField(default='0',blank=False,null=True)
    total_inventory      = models.IntegerField(default='0',blank=True,null=True)
    eoq                  = models.IntegerField(default='0',blank=True,null=True)
    no_of_workingdays    = models.IntegerField(default='300',blank=True,null=True)
    rq                   = models.IntegerField(default='0',blank=True,null=True)
    z                    = models.DecimalField(max_digits=4,decimal_places=3,default='0',blank=True,null=True)

    def __str__(self):
        return str(self.name)
    
    def save(self, *args, **kwargs):
        self.name = self.name.upper()
        a = 2*float(self.no_of_workingdays)*float(self.average_daily_demand)*float(self.ordering_cost)
        b = float(self.unit_costprice)*float(self.carrying_cost)/100
        self.eoq  = math.sqrt(a/b)
        self.z    = (st.norm.ppf(self.service_level/100))
        self.rq   = (self.lead_time*self.average_daily_demand)+(self.z*self.standard_deviation*(self.lead_time))
        return super().save(*args, **kwargs)

class Purchase(models.Model):
    user        = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name="demand")
    product     = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="demands")
    price       = models.PositiveIntegerField(blank=False,null=True)
    quantity    = models.IntegerField(blank=False,null=True)
    total_price = models.PositiveIntegerField(blank=True)
    date        = models.DateTimeField(default=timezone.now, editable=True)    
    recieved    = models.IntegerField(default='0',blank=False,null=True)


    def save(self, *args, **kwargs):
        self.total_price = self.quantity * self.price
        super().save(*args, **kwargs)

    def __str__(self):
        return "sold {} - {} items for {}".format(self.product.name, self.quantity, self.total_price)

products/forms.py
from django import forms
from .models import Purchase, Product
from os import name
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models import fields
from django.http import request


class PurchaseForm(forms.ModelForm):
    class Meta:
        model  = Purchase
        fields = ['product', 'quantity', 'price', 'recieved', 'date']

    def __init__(self,user=None,*args,**kwargs):
        super(PurchaseForm,self).__init__(*args,**kwargs)
        if user:
            self.fields['product'].queryset=Product.objects.filter(user=user)

class ItemsForm(forms.ModelForm):
    class Meta:
        model  = Product
        fields = ['name','average_daily_demand','unit_costprice','carrying_cost','ordering_cost','total_inventory','lead_time','service_level','standard_deviation','no_of_workingdays']

    def clean_name(self):
        name = self.cleaned_data.get('name').upper()
        return name

class ItemSearchForm(forms.ModelForm):
   class Meta:
        model = Product
        fields = ['name']

products/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models.aggregates import Avg, StdDev,Sum,Variance
from django.db.models.expressions import F
from django.views.generic import TemplateView, View 
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http import HttpResponse
from .models import Product, Purchase
from .utils import get_simple_plot, get_salesman_from_id, get_image
from numpy.core.fromnumeric import product
from .forms import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

# Create your views here.

@login_required(login_url='login')
def sales_dist_view(request):
    df = pd.DataFrame(Purchase.objects.all().values())
    print(df)
    df['user_id']=df['user_id'].apply(get_salesman_from_id)
    df.rename({'user_id':'user'}, axis=1, inplace=True)
    df['date'] = df['date'].apply(lambda x: x.strftime('%Y-%m-%d'))
    
    plt.switch_backend('Agg')
    plt.xticks(rotation=90)
    sns.barplot(x='date', y='total_price', hue='user', data=df)
    plt.tight_layout
    graph = get_image()

    #return HttpResponse("Hello Salesman")
    return render(request, 'products/sales.html', {'graph':graph})

@login_required(login_url='login')
def chart_select_view(request):
    error_message = None
    df = None
    graph = None
    price = None

    product_df = pd.DataFrame(Product.objects.all().values())
    purchase_df = pd.DataFrame(Purchase.objects.all().values())
    if product_df.shape[0]>0 :
        product_df['product_id'] = product_df['id']
    
    if purchase_df.shape[0]>0 :
        df = pd.merge(purchase_df, product_df, on='product_id').drop(['id_y', 'date_y'], axis=1).rename({'id_x':'id', 'date_x':'date'}, axis=1)
        price = df['price']
        if request.method == 'POST':
            chart_type = request.POST.get('sales')
            date_from  = request.POST.get('date_from') 
            date_to    = request.POST.get('date_to')

            df['date'] = df['date'].apply(lambda x: x.strftime('%Y-%m-%d'))
            df2 = df.groupby('date', as_index=False)['total_price'].agg('sum')

            if chart_type!="":
                if date_from!="" and date_to!="":
                    df = df[(df['date']>date_from)&(df['date']<date_to)]
                    df2 = df.groupby('date', as_index=False)['total_price'].agg('sum')
                # function to get a graph
                graph = get_simple_plot(chart_type, x=df2['date'], y=df2['total_price'] ,data=df)
            else:
                error_message = 'please select a chart to continue'

    else:
        error_message = 'no records in database'
        
    context ={
        'error_message': error_message,
        'graph' : graph,
        'price' : price,
        #'products' : product_df.to_html(),
        #'purchase' : purchase_df.to_html(),
        #'df'       : df,
    }
    return render(request, 'products/main.html', context)

@login_required(login_url='login')
def add_purchase_view(request):
        form=PurchaseForm(request.user)
        if request.method == 'POST':
            form=PurchaseForm(request.user,request.POST) 
            if form.is_valid():
                n = form.cleaned_data["product"]
                l = form.cleaned_data["quantity"]
                c = form.cleaned_data["price"]
                o = form.cleaned_data["recieve_quantity"]
                d = form.cleaned_data["date"]

                reporter = request.user.products.get(name=n)
                reporter.total_inventory = F('total_inventory')-l+o
                reporter.save()
                t = Purchase(product=n,quantity=l,price=c,recieve_quantity=o,date=d)
                t.save()
                request.user.purchases.add(t)

                return redirect('products:add-purchase-view')
                    
        return render(request,'products/add.html',context={'form':PurchaseForm(request.user) })

@login_required(login_url='login')
def items_list(request):
    ite   = None
    total = None

    try:
        ite = request.user.items.all()
        #ite = Product.objects.all()
    except ObjectDoesNotExist:
        messages.info(request,"There are no items.....")
    form = ItemSearchForm(request.POST or None)

    if request.method == 'POST':
            try:
                ite = request.user.items.filter(name__icontains=form['name'].value())
            except ObjectDoesNotExist:
                messages.info(request,"There are no items.....")
    
    context = {
        "form": form,
        "items":ite,
        "total":total
    }
    return render(request,'products/items_list.html',context)

@login_required(login_url='login')
def demand_list(request,*args,**kwargs):
    itee=None
    
    try:
        itee=request.user.demand.all()
    except ObjectDoesNotExist:
        messages.info(request,"No purchases has been recorded.....")

    return render(request,'products/demand_list.html',context={'demand':itee})

@login_required(login_url='login')
def DemandCreate(request):
        form = PurchaseForm(request.user)

        if request.method == 'POST':
            form = PurchaseForm(request.user,request.POST) 
            if form.is_valid():
                n = form.cleaned_data["product"]
                l = form.cleaned_data["quantity"]
                c = form.cleaned_data["price"]
                o = form.cleaned_data["recieved"]
                d = form.cleaned_data["date"]

                reporter = request.user.items.get(name=n)
                reporter.total_inventory = F('total_inventory')-l+o
                reporter.save()
                t = Purchase(product=n,quantity=l,price=c,recieved=o,date=d)
                t.save()
                request.user.demand.add(t)

                return redirect('product:demand_create_url')
                    
        return render(request,'products/demand_create.html',context={'form':PurchaseForm(request.user) })

@login_required(login_url='login')
def ItemCreate(request):
        form = ItemsForm()
        if request.method == 'POST':
            form=ItemsForm(request.POST) 
            if form.is_valid():
                n = form.cleaned_data["name"]
                l = form.cleaned_data["lead_time"]
                c = form.cleaned_data["carrying_cost"]
                o = form.cleaned_data["ordering_cost"]
                t = form.cleaned_data["total_inventory"]
                u = form.cleaned_data["unit_costprice"]
                s = form.cleaned_data["service_level"]
                w = form.cleaned_data["no_of_workingdays"]
                d = form.cleaned_data["standard_deviation"]
                a = form.cleaned_data["average_daily_demand"]

                for i in request.user.items.all():
                    if i.name==n:
                        messages.error(request, n +' Item Already Created')
                        return redirect('products:item_create_url')
              
                t = Product(name=n,lead_time=l,average_daily_demand=a,carrying_cost=c,ordering_cost=o,total_inventory=t,unit_costprice=u,service_level=s,no_of_workingdays=w,standard_deviation=d)
                t.save()
                request.user.items.add(t) 
                messages.success(request, n +' Item Created')
                return redirect('products:items_list_url')
                    
        return render(request,'products/item_create.html',context={'form':form, 'product_message':None })

@login_required(login_url='login')
def delete_items(request,pk):
    query_set = Product.objects.get(id=pk)
    
    if request.method =='POST':
        query_set.delete()
        messages.success(request,query_set.name + ' Removed')
        return redirect('products:items_list_url')
    
    context={
        'item':query_set.name
        }
    return render(request,'products/delete_items.html',context)

@login_required(login_url='login')
def update_items(request,pk):
    query_set = Product.objects.get(id=pk)
    form      = ItemsForm(instance=query_set)
    n         = query_set.name
    
    if request.method=='POST':
        form = ItemsForm(request.POST,instance=query_set)
        if form.is_valid():
            form.save()
            messages.info(request, n + '  Updated to ' + query_set.name)
            return redirect('products:items_list_url')
    
    context={
        'form':form
    }
    return render(request,'products/update_item.html',context)

@login_required(login_url='login')
def calculations(request):
    item_df   = pd.DataFrame(Product.objects.all().values().filter(user=request.user))
    demand_df = pd.DataFrame(Purchase.objects.all().values().filter(user=request.user))
    
    if demand_df.shape[0]>0:
        item_df['item_id'] = item_df['id']
        df = pd.merge(item_df,demand_df,on='item_id').drop(['id_y','id_x','carrying_cost','ordering_cost','unit_costprice','lead_time','service_level','standard_deviation','average_daily_demand','total_inventory','eoq','no_of_workingdays','rq','z','user_id_y','price','recieve_quantity'],axis=1).rename({'item_id':'id'},axis=1)
        del df['user_id_x']
        del df['id']
        df.rename(columns = {'date':'End of the Month'}, inplace = True)
        df.rename(columns = {'name':'Item Name'}, inplace = True)
        df['End of the Month'] = pd.to_datetime(df['End of the Month'])
        df = df.groupby([pd.Grouper(key='End of the Month', freq='1M'),'Item Name']).aggregate({'quantity':['mean','std','count','sum']}) # groupby each 1 month
        df.rename(columns = {'quantity':'Demand'}, inplace = True) 
        df.rename(columns = {'mean':'Daily Average'}, inplace = True) 
        df.rename(columns = {'std':'Standard deviation'}, inplace = True) 
        df.rename(columns = {'count':'Frequency'}, inplace = True) 

products/templates/products/add.html
{% extends 'base1.html'%}

{% block title %} 
        add purchase
{% endblock title %}

{% block content %}
    {% if added_message %}
        <div class="ui success message">
            <i class="close icon"></i>
            <div class="header">{{ added_message }}</div>
        </div>    
    {% endif %}
    <h1>Add</h1>
    <form action="" method="POST" class="ui form">
        {% csrf_token %}
        {{ form }}
        <button type='submit' class="ui positive button block-center mtop">Add sales</button>
    </form>
{% endblock content%}

products/templates/products/add_inventory.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Add Inventory</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="Submit">
    </form>
{% endblock %}

products/templates/products/add_items.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Issue Item</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="Submit">
    </form>
{% endblock %}

products/templates/products/calculations.html
{% extends 'base.html' %}

{% block title  %} Items List {% endblock %}

{% block content  %}
    {{df2|safe}}
{% endblock %}

products/templates/products/chart.html
{% extends 'base.html' %}

{% block content  %}
<h1>Pie Chart Population</h1>

  <canvas id="myChart" width="400" height="400"></canvas>

 <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script><script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
 </script>

  {{ df | safe}}


  <form action="{% url 'chart_url' %}" method="post" class="ui form">
      {% csrf_token %}

      <div class="fields">
        <div class="two fields">
          <label for="">date from :</label>
          <input type="date" name="date_from">
        </div>
        <div class="fields">
          <label for="">date to:</label>
          <input type="date" name="date_to">
        </div>
      </div>

      <button type="submit" name="button">Sunmit</button>
  </form>




          
{% endblock %}

products/templates/products/delete_items.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <h1>Are you sure you want to delete.......... Item :  {{ item }}</h1><br>
        <input class="btn btn-danger" type="submit" value="Yes" />
        <a href="{% url 'products:items_list_url' %}"><div class="btn btn-primary">Cancel</div></a>
    </form>
{% endblock %}

products/templates/products/demand_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Sales</h1>
    <br>
    <br>
    {% for message in messages %}
        <div class="alert alert-danger" role="alert">
          {{message}}
        </div>
    {%endfor%}
    <form method='POST' action=''>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value='Create'/>
    </form>
{% endblock %}

products/templates/products/demand_list.html
{% extends 'base.html' %}

{% block title  %} Items List {% endblock %}

{% block content  %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Time</th>
      </tr>
    </thead>
    
    {% for d in demand %}
    <tbody>
      <tr>
        <th scope="row">{{ d.product }}</th>
        <td>{{ d.price }}</td>
        <td>{{d.quantity}}</td>
        <td>{{d.date}}</td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
{% endblock %}

products/templates/products/item_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Create Item</h1>
    {% if product_message %}
        <div class="ui success message">
            <i class="close icon"></i>
            <div class="header">{{ product_message }}</div>
        </div>
    {% endif %}
    <br>
    <br>
    {% for message in messages %}
        <div class="alert alert-danger" role="alert">
          {{message}}
        </div>
    {%endfor%}
    <form method='POST' action=''>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value='Create'/>
    </form>
{% endblock %}

products/templates/products/items_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title  %} Items List {% endblock %}

{% block content  %}

  {% for message in messages %}
    <div class="alert alert-danger" role="alert">
      {{message}}
    </div>
  {%endfor%}

  <form method='POST' action=''>
    {% csrf_token %}
    {{form|crispy}}
        <input type="submit" class="btn btn-info" value='Search'/>
  </form>

  <br>
    <a href="{% url 'products:items_list_url' %}" class="btn btn-primary btn-lg " role="button" >Show all Items</a>
    <a href="{% url 'products:item_create_url' %}" class="btn btn-secondary btn-lg "  role="button">Add new Item</a>

    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Inventory</th>
          <th scope="col">EOQ</th>
          <th scope="col">Reorder Quantity</th>
        </tr>
      </thead>

      {% for item in items %}
          <tbody>
            <tr>
              <th scope="row">{{ item.name }}</th>
              <td>{{item.total_inventory}}</td>
              <td>{{item.eoq}}</td>
              <td>{{item.rq}}</td>
              <td><a href="{% url 'products:update_item' item.id %}" class="btn btn-outline-secondary" role="button">Update</a></td>
              <td><a href="{% url 'products:delete_items' item.id %}" class="btn btn-outline-danger" role="button">Delete</a></td>
            </tr>
          </tbody>
      {% endfor %}
    </table>

{% endblock %}

products/templates/products/main.html
{% extends 'base1.html'%}

{% block title %} 
        
{% endblock title %}

{% block content %} 
    <div class="ui modal mymodal">
        <div class="header"><h1>Price data</h1></div>
        <div class="ui container">
            <ul>
                <li><strong>Count: </strong>{{ price.count}}</li>
                <li><strong>Mean: </strong>{{ price.mean}}</li>
                <li><strong>Std dev: </strong>{{ price.std|floatformat}}</li>
            </ul>
        </div>
    </div>
    <div>
        <div class="block-center">
            {% if error_message %}
                <!--linked with java script code in main.js-->
                <div class="ui negative message">
                    <i class="close icon"></i>
                    <div class="header">{{ error_message }}</div>
                </div>
            {% endif %}

            {% if request.POST %}
                {% if graph %}
                    <img src="data:image/png;base64, {{ graph | safe}}">
                {% endif %}
            {% endif %}
        </div>
        <form action="" method="POST" class="ui form">
            {% csrf_token %}
            <div class="field">
                <label>Choose a chart type: </label>
                <div class="ui selection dropdown">
                    <input type="hidden" name="sales">
                    <i class="dropdown icon"></i>
                    <div class="default text">----</div>
                    <div class="menu">
                        <div class="item" value="bar">Bar plot</div>
                        <div class="item" value="line">Line plot</div>
                        <div class="item" value="count">Count plot</div>
                    </div>
                </div>
            </div>
            <div class="field">
                <div class="two fields">
                    <div class="field">
                        <label>Date from: </label>
                        <input type="date" name="date_from">
                    </div>
                    <div class="field">
                        <label>Date to: </label>
                        <input type="date" name="date_to">
                    </div>
                </div>
            </div>
            <div class="block-center">
                <button class='ui primary button' type="submit">Select</button>
            </div>
        </form>
        <div class="block-center">
            <button class='ui secondary button' id='modal-btn'>See summary</button>
            <br>
            <a href={% url 'products:add-purchase-view' %}><button class="ui positive button">Add records</button></a>
        </div>
    </div>
{% endblock content %}

products/templates/products/sales.html
{% extends 'base1.html'%}

{% block title %}sales{% endblock title %}

{% block content %}
<h1>Sales</h1>
{% if graph %}
    <img src="data:image/png;base64, {{ graph | safe}}">
{% endif %}
{% endblock content %}

products/templates/products/update_item.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Update Item</h1>
    <br>
    <br>
    {% for message in messages %}
        <div class="alert alert-danger" role="alert">
          {{message}}
        </div>
    {%endfor%}
    <form method='POST' action=''>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value='Create'/>
    </form>
{% endblock %}

products/templates/products/view.html
{% extends 'base1.html' %}

{% block title %} View {% endblock %}

{% block content %}
    {% for td in user.todolist.all %}
	    <p>{{td.name}}</p>
    {% endfor %}
{% endblock %}